name: Auto Format with ESLint
run-name: ESLint Formatter
on: [push, pull_request]

jobs:
  setup-npm:
    runs-on: ubuntu-latest
    steps:
      - run: npm init -y && npm install
      - run: npm install --save-dev eslint eslint-config-airbnb eslint-plugin-import
      - run: echo "Successfully set up npm project"
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - run: npm run pretest
      - run: echo "Successfully ran the pretest script"
